# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JndR8j1fE-fOiXW-1_SPVfY_iN2APziW
"""

from fastapi import FastAPI

app = FastAPI()

@app.get("/prompt")
def predict_model(age: int, sex: str):
  if age <15 or sex == "F":
    return {'survived': 1}
  else:
    return {'survived': 0}