# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VkliVvYRwg3rZ29Ln6wIU1PhVfF1Muwm
"""

import requests

age = 15
sex = "F"

response = requests.get(f"http://127.0.0.1:8000/prompt?age={age}&sex={sex}")
output = response.json()
print(output)